openapi: 3.0.1
info:
  title: Filter_API
  description: API Definition of Filter_API
  version: 1.0.0
servers:
- url: http://localhost:8290/num
paths:
  /:
    post:
      responses:
        default:
          description: Default response
